server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: m1
          uri: http://localhost:8081/
          predicates:
            - Path=/m1
        - id: m2
          uri: http://localhost:8082/
          predicates:
            - Path=/m2
